import { Alert, Geofence, Department } from "@/types"

export const mockDepartments: Department[] = [
  { id: "dept-001", name: "Irrigation Development Division", code: "IDD" },
  { id: "dept-002", name: "Lowlands Management Division", code: "LMD" },
  { id: "dept-003", name: "ICT Department", code: "ICT" },
  { id: "dept-004", name: "Finance", code: "FIN" },
  { id: "dept-005", name: "HR", code: "HR" },
]

export const mockAlerts: Alert[] = [
  {
    id: "alert-001",
    type: "maintenance_due",
    title: "Maintenance Due — AA 12345",
    message: "Vehicle AA 12345 (Toyota Land Cruiser) is within 500 km of its next scheduled maintenance at 80,000 km.",
    vehicleId: "veh-001",
    severity: "warning",
    isRead: false,
    createdAt: new Date("2026-06-06T08:30:00"),
  },
  {
    id: "alert-002",
    type: "insurance_expiry",
    title: "Insurance Expiring Soon",
    message: "Insurance for vehicle OR 23456 expires on July 15, 2026. Renewal required within 30 days.",
    vehicleId: "veh-003",
    severity: "warning",
    isRead: false,
    createdAt: new Date("2026-06-05T14:20:00"),
  },
  {
    id: "alert-003",
    type: "fuel_low",
    title: "Low Fuel Alert",
    message: "Vehicle AM 34567 fuel level is critically low at 8 liters (10% capacity).",
    vehicleId: "veh-005",
    severity: "critical",
    isRead: false,
    createdAt: new Date("2026-06-06T16:45:00"),
  },
  {
    id: "alert-004",
    type: "geofence_breach",
    title: "Geofence Violation Detected",
    message: "Vehicle TG 45678 has exited the designated Addis Ababa geofence zone at 15:32.",
    vehicleId: "veh-007",
    driverId: "drv-007",
    severity: "critical",
    isRead: false,
    createdAt: new Date("2026-06-06T15:32:00"),
  },
  {
    id: "alert-005",
    type: "incident",
    title: "New Incident Report Filed",
    message: "Incident reported for vehicle DD 56789 — minor collision at Bole Road intersection. Driver Solomon uninjured.",
    vehicleId: "veh-001",
    driverId: "drv-001",
    severity: "critical",
    isRead: false,
    createdAt: new Date("2026-06-04T09:15:00"),
  },
  {
    id: "alert-006",
    type: "license_expiry",
    title: "Driver License Expiring",
    message: "Driver Henok Mesfin's license expires on June 15, 2026. Renewal action required immediately.",
    driverId: "drv-008",
    severity: "warning",
    isRead: true,
    createdAt: new Date("2026-06-01T10:00:00"),
  },
  {
    id: "alert-007",
    type: "maintenance_request",
    title: "New Maintenance Request",
    message: "Driver Tadesse Worku submitted a maintenance request for vehicle SM 67890 — brake system issues.",
    vehicleId: "veh-004",
    driverId: "drv-004",
    severity: "info",
    isRead: true,
    createdAt: new Date("2026-06-03T11:30:00"),
  },
  {
    id: "alert-008",
    type: "fuel_request",
    title: "Fuel Request Pending Approval",
    message: "Fuel request for 60 liters diesel for vehicle AF 78901 is pending approval from transport expert.",
    vehicleId: "veh-006",
    severity: "info",
    isRead: false,
    createdAt: new Date("2026-06-05T13:00:00"),
  },
  {
    id: "alert-009",
    type: "maintenance_due",
    title: "Overdue Maintenance Warning",
    message: "Vehicle SD 89012 has exceeded its maintenance schedule by 1,200 km. Immediate service required.",
    vehicleId: "veh-009",
    severity: "critical",
    isRead: false,
    createdAt: new Date("2026-06-06T07:00:00"),
  },
  {
    id: "alert-010",
    type: "insurance_expiry",
    title: "Insurance Expired",
    message: "Insurance for vehicle GM 90123 expired on May 30, 2026. Vehicle must not be deployed until renewed.",
    vehicleId: "veh-010",
    severity: "critical",
    isRead: true,
    createdAt: new Date("2026-05-31T08:00:00"),
  },
  {
    id: "alert-011",
    type: "fuel_low",
    title: "Low Fuel Warning",
    message: "Vehicle BG 01234 fuel level at 15 liters (19% capacity). Refueling recommended before next deployment.",
    vehicleId: "veh-011",
    severity: "warning",
    isRead: false,
    createdAt: new Date("2026-06-06T12:15:00"),
  },
  {
    id: "alert-012",
    type: "maintenance_request",
    title: "Urgent Maintenance Request",
    message: "Critical maintenance request submitted for vehicle HR 12345 — engine overheating issue reported during field trip.",
    vehicleId: "veh-012",
    severity: "critical",
    isRead: false,
    createdAt: new Date("2026-06-06T14:00:00"),
  },
  {
    id: "alert-013",
    type: "geofence_breach",
    title: "Route Deviation Detected",
    message: "Vehicle AA 23456 deviated from its assigned route near Adama. Currently 15 km off designated path.",
    vehicleId: "veh-002",
    driverId: "drv-002",
    severity: "warning",
    isRead: true,
    createdAt: new Date("2026-06-02T16:00:00"),
  },
  {
    id: "alert-014",
    type: "license_expiry",
    title: "Multiple Licenses Expiring",
    message: "3 driver licenses expire within the next 60 days. Review driver license report for details.",
    severity: "info",
    isRead: false,
    createdAt: new Date("2026-06-01T09:00:00"),
  },
  {
    id: "alert-015",
    type: "incident",
    title: "Incident Under Investigation",
    message: "Incident INC-006 involving vehicle veh-006 near Gambella is under investigation. Insurance claim filed.",
    vehicleId: "veh-006",
    driverId: "drv-006",
    severity: "warning",
    isRead: true,
    createdAt: new Date("2026-05-28T10:30:00"),
  },
]

export const mockGeofences: Geofence[] = [
  {
    id: "gf-001",
    name: "Addis Ababa City Boundary",
    description: "Metropolitan boundary for Addis Ababa deployed vehicles",
    vehicleIds: ["veh-001", "veh-002", "veh-003", "veh-007", "veh-008"],
    boundaries: [
      { lat: 9.08, lng: 38.68 },
      { lat: 9.08, lng: 38.84 },
      { lat: 8.92, lng: 38.84 },
      { lat: 8.92, lng: 38.68 },
    ],
    isActive: true,
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "gf-002",
    name: "Oromia Field Operations Zone",
    description: "Operational area for field vehicles in Oromia region",
    vehicleIds: ["veh-004", "veh-005", "veh-010"],
    boundaries: [
      { lat: 9.50, lng: 37.00 },
      { lat: 9.50, lng: 40.00 },
      { lat: 7.00, lng: 40.00 },
      { lat: 7.00, lng: 37.00 },
    ],
    isActive: true,
    createdAt: new Date("2025-04-15"),
  },
  {
    id: "gf-003",
    name: "Afar Lowlands Corridor",
    description: "Designated corridor for vehicles operating in Afar lowlands",
    vehicleIds: ["veh-006", "veh-009", "veh-013"],
    boundaries: [
      { lat: 12.50, lng: 39.50 },
      { lat: 12.50, lng: 42.00 },
      { lat: 10.50, lng: 42.00 },
      { lat: 10.50, lng: 39.50 },
    ],
    isActive: true,
    createdAt: new Date("2025-06-01"),
  },
  {
    id: "gf-004",
    name: "SNNPR Project Sites",
    description: "Southern Nations project areas including Omo Valley operations",
    vehicleIds: ["veh-011", "veh-014"],
    boundaries: [
      { lat: 7.50, lng: 36.00 },
      { lat: 7.50, lng: 38.50 },
      { lat: 5.50, lng: 38.50 },
      { lat: 5.50, lng: 36.00 },
    ],
    isActive: false,
    createdAt: new Date("2025-08-10"),
  },
]
