import { Company } from "@/types"

export const mockCompanies: Company[] = [
  {
    id: "com-001",
    name: "Ministry of Irrigation and Lowlands Headquarters",
    code: "MILL-HQ",
    type: "headquarters",
    address: "Arat Kilo, Addis Ababa",
    phone: "+251111223344",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "com-002",
    name: "Adama Regional Logistics Node",
    code: "MILL-AD",
    type: "regional_office",
    address: "Adama, Oromia",
    phone: "+251221122334",
    isActive: true,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "com-003",
    name: "Hawassa Basin Research Station",
    code: "MILL-HW",
    type: "station",
    address: "Hawassa, Sidama",
    phone: "+251462211223",
    isActive: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "com-004",
    name: "Bahir Dar Irrigation Support Node",
    code: "MILL-BD",
    type: "logistics_node",
    address: "Bahir Dar, Amhara",
    phone: "+251582201122",
    isActive: true,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "com-005",
    name: "Dire Dawa Field Office",
    code: "MILL-DD",
    type: "regional_office",
    address: "Dire Dawa",
    phone: "+251251112233",
    isActive: true,
    createdAt: new Date("2024-04-20"),
  },
]
