import { User } from "@/types"

export const mockUsers: User[] = [
  {
    id: "usr-001",
    name: "Abebe Kebede",
    email: "superadmin@mill.gov.et",
    role: "super_admin",
    department: "ICT Department",
    phone: "+251911234567",
    createdAt: new Date("2024-01-15"),
    isActive: true,
  },
  {
    id: "usr-002",
    name: "Tigist Haile",
    email: "manager@mill.gov.et",
    role: "basic_service_manager",
    department: "Irrigation Development Division",
    phone: "+251912345678",
    createdAt: new Date("2024-02-01"),
    isActive: true,
  },
  {
    id: "usr-003",
    name: "Dawit Mengistu",
    email: "deployhead@mill.gov.et",
    role: "transport_deployment_head",
    department: "Lowlands Management Division",
    phone: "+251913456789",
    createdAt: new Date("2024-03-10"),
    isActive: true,
  },
  {
    id: "usr-004",
    name: "Meron Tadesse",
    email: "expert@mill.gov.et",
    role: "transport_deployment_expert",
    department: "Lowlands Management Division",
    phone: "+251914567890",
    createdAt: new Date("2024-03-15"),
    isActive: true,
  },
  {
    id: "usr-005",
    name: "Yonas Bekele",
    email: "mechanic@mill.gov.et",
    role: "maintenance_expert",
    department: "Irrigation Development Division",
    phone: "+251915678901",
    createdAt: new Date("2024-04-01"),
    isActive: true,
  },
  {
    id: "usr-006",
    name: "Solomon Girma",
    email: "driver@mill.gov.et",
    role: "driver",
    department: "Lowlands Management Division",
    phone: "+251916789012",
    createdAt: new Date("2024-04-15"),
    isActive: true,
  },
  {
    id: "usr-007",
    name: "Hanna Wolde",
    email: "hanna.w@mill.gov.et",
    role: "transport_deployment_expert",
    department: "Finance",
    phone: "+251917890123",
    createdAt: new Date("2024-05-01"),
    isActive: true,
  },
  {
    id: "usr-008",
    name: "Kidist Alemu",
    email: "kidist.a@mill.gov.et",
    role: "ict_department",
    department: "ICT Department",
    phone: "+251918901234",
    createdAt: new Date("2024-05-15"),
    isActive: true,
  },
  {
    id: "usr-009",
    name: "Bereket Tesfaye",
    email: "bereket.t@mill.gov.et",
    role: "driver",
    department: "Irrigation Development Division",
    phone: "+251919012345",
    createdAt: new Date("2024-06-01"),
    isActive: true,
  },
  {
    id: "usr-010",
    name: "Selam Negash",
    email: "selam.n@mill.gov.et",
    role: "basic_service_manager",
    department: "HR",
    phone: "+251910123456",
    createdAt: new Date("2024-06-15"),
    isActive: false,
  },
]
