import { User, UserRole } from "@/types"

export const mockUsers: User[] = [
  {
    id: "usr-001",
    name: "Abebe Kebede",
    email: "superadmin@fleet.com",
    role: UserRole.SUPER_ADMIN,
    department: "ICT Department",
    phone: "+251911234567",
    createdAt: new Date("2024-01-15"),
    isActive: true,
  },
  {
    id: "usr-002",
    name: "Tigist Haile",
    email: "manager@fleet.com",
    role: UserRole.BASIC_SERVICE_MANAGER,
    department: "Irrigation Development Division",
    phone: "+251912345678",
    createdAt: new Date("2024-02-01"),
    isActive: true,
  },
  {
    id: "usr-003",
    name: "Dawit Mengistu",
    email: "deployhead@fleet.com",
    role: UserRole.TRANSPORT_DEPLOYMENT_HEAD,
    department: "Lowlands Management Division",
    phone: "+251913456789",
    createdAt: new Date("2024-03-10"),
    isActive: true,
  },
  {
    id: "usr-004",
    name: "Meron Tadesse",
    email: "expert@fleet.com",
    role: UserRole.TRANSPORT_DEPLOYMENT_EXPERT,
    department: "Lowlands Management Division",
    phone: "+251914567890",
    createdAt: new Date("2024-03-15"),
    isActive: true,
  },
  {
    id: "usr-005",
    name: "Yonas Bekele",
    email: "mechanic@fleet.com",
    role: UserRole.MAINTENANCE_EXPERT,
    department: "Irrigation Development Division",
    phone: "+251915678901",
    createdAt: new Date("2024-04-01"),
    isActive: true,
  },
  {
    id: "usr-006",
    name: "Solomon Girma",
    email: "driver@fleet.com",
    role: UserRole.DRIVER,
    department: "Lowlands Management Division",
    phone: "+251916789012",
    createdAt: new Date("2024-04-15"),
    isActive: true,
  },
  {
    id: "usr-007",
    name: "Hanna Wolde",
    email: "hanna.w@fleet.com",
    role: UserRole.TRANSPORT_DEPLOYMENT_EXPERT,
    department: "Finance",
    phone: "+251917890123",
    createdAt: new Date("2024-05-01"),
    isActive: true,
  },
  {
    id: "usr-008",
    name: "Kidist Alemu",
    email: "kidist.a@fleet.com",
    role: UserRole.ICT_DEPARTMENT,
    department: "ICT Department",
    phone: "+251918901234",
    createdAt: new Date("2024-05-15"),
    isActive: true,
  },
  {
    id: "usr-009",
    name: "Bereket Tesfaye",
    email: "bereket.t@fleet.com",
    role: UserRole.DRIVER,
    department: "Irrigation Development Division",
    phone: "+251919012345",
    createdAt: new Date("2024-06-01"),
    isActive: true,
  },
  {
    id: "usr-010",
    name: "Selam Negash",
    email: "selam.n@fleet.com",
    role: UserRole.BASIC_SERVICE_MANAGER,
    department: "HR",
    phone: "+251910123456",
    createdAt: new Date("2024-06-15"),
    isActive: false,
  },
  {
    id: "usr-011",
    name: "Alemayehu Tesema",
    email: "user@fleet.com",
    role: UserRole.USER,
    department: "Logistics",
    phone: "+251911123456",
    createdAt: new Date("2024-06-20"),
    isActive: true,
  },
]
