spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fms_tracking
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:29092
  jpa:
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

server:
  port: 8084
